import { Toaster } from "react-hot-toast";
import Providers from "../Providers";
import "../globals.css";

export const metadata = {
  title: "Admin profile",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <Toaster position="top-right" reverseOrder={false} />
          <div className="container mx-auto xl:max-w-screen-2xl">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
