import "../globals.css";
import { Inter } from "next/font/google";
import Providers from "../Providers";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Shopping Project",
  description: "Generated by Mojtaba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} bg-gray-100`}
      >
        <Providers>
          <Header />
          <Toaster position="top-right" reverseOrder={false} />
          <div className="container mx-auto xl:max-w-screen-2xl">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
